


spring.datasource.url=jdbc:postgresql://schoolsystem_ccc9_user:U5zRQFJcJUL5vqYCf0iyhZ0RvSD6j1eQ@dpg-d7ah0i15pdvs73ea7ov0-a/schoolsystem_ccc9
spring.datasource.username=schoolsystem_ccc9_user
spring.datasource.password=U5zRQFJcJUL5vqYCf0iyhZ0RvSD6j1eQ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.error.include-message=always
spring.application.name=SchoolSystem
#spring.datasource.url=jdbc:mysql://localhost:3306/BookLoan
#spring.datasource.username=bookLoan
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.open-in-view=false
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#
#server.error.include-message=always